bump_version: null
lint:
  template_strings:
    - modules/local/report/create/app/templates/tf.html
    - modules/local/report/create/app/templates/tg.html
    - modules/local/report/create/app/templates/macros.html
    - modules/local/report/create/app/templates/configuration.html
    - modules/local/report/create/app/templates/snp.html
    - modules/local/report/create/app/templates/base.html
    - modules/local/report/create/app/templates/network.html
  files_unchanged:
    - ".github/CONTRIBUTING.md"
    - "assets/sendmail_template.txt"
  files_exist:
    - "assets/multiqc_config.yml"
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Nico Trummer
  description: TBD
  force: false
  is_nfcore: true
  name: tfactivity
  org: nf-core
  outdir: .
  skip_features:
    - fastqc
    - multiqc
  version: 0.0.1dev
update: null
